plugins { id 'com.android.application' }

android {
 namespace 'com.powerduck.jinjugame'
 compileSdk 35
 defaultConfig {
  applicationId 'com.powerduck.jinjugame.unlocked'
  minSdk 26
  targetSdk 35
  versionCode 104
  versionName '2.4.9-unlocked-gradle'
 }
 sourceSets {
  main.java.srcDirs = ['../common-src']
  main.res.srcDirs = ['../common-res', 'src/main/res']
 }
 compileOptions {
  sourceCompatibility JavaVersion.VERSION_17
  targetCompatibility JavaVersion.VERSION_17
 }
 buildTypes { release { minifyEnabled false } }
}

dependencies {
 implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
 implementation 'com.google.zxing:core:3.5.3'
}
