plugins { id 'com.android.application' }

android {
 namespace 'com.powerduck.jinjugame'
 compileSdk 35
 defaultConfig {
  applicationId 'com.powerduck.jinjugame.unlocked249'
  minSdk 26
  targetSdk 28
  versionCode 105
  versionName '2.4.9-unlocked-verified-shell'
 }
 sourceSets {
  main.java.srcDirs = ['../common-src']
  main.res.srcDirs = ['../common-res', 'src/main/res']
 }
 compileOptions {
  sourceCompatibility JavaVersion.VERSION_17
  targetCompatibility JavaVersion.VERSION_17
 }
 buildTypes { release { minifyEnabled false } }
}

dependencies { }
